application: anniecake99
version: 1
runtime: php
api_version: 1

handlers: 
#- url: /(.*\.css)
#  mime_type: text/css
#  static_files: static/\1
#  upload: static/(.*\.css)
  
#- url: /(.*\.js)
#  mime_type: text/javascript
#  static_files: static/\1
#  upload: static/(.*\.js)

# image files
#- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
#  static_files: static/\1
#  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.+\.php)(.*)
  script: \1

- url: /static
  static_dir: static

- url: /.*
  script: index.php
